sudo: false

language: scala
jdk: oraclejdk8

script:
  - sbt ^test

cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.coursier
    - $HOME/.ivy2/cache

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.coursier -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm